[package]
name = "stellar_empire_legacy_core"
version = "0.1.0"
edition = "2021"
authors = ["Aleksandr Kugushev kugushew@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
